version: '3'
services:
  python_ocr:
    # restart: always
    build:
      context: .
      dockerfile: Dockerfile
    image: python38_ocr
    container_name: python_ocr
    working_dir: '/Projects'
    tty: true
    volumes:
      - ./Projects:/Projects
    ports: 
      - '8080:8080'
    command: jupyter-lab --ip 0.0.0.0 --port=8080 --allow-root --no-browser --NotebookApp.token=''
