version: '3'
services:
  python_env:
    build:
      context: .
      dockerfile: Dockerfile
    image: ubuntu-python39
    container_name: pystan3
    volumes:
      - ./Projects:/work
    ports:
      - '8888:8888'
    working_dir: /work
    command: jupyter lab --ip=0.0.0.0 --allow-root --LabApp.token=''
