# 使用できないので、docker build -> docker run で。。。

version: '3'
services:
  python_env:
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    image: python-opencv
    container_name: python-opencv
    volumes:
      - ./Projects:/work
      - ~/.Xauthority:/root/.Xauthority

    ports:
      - '8888:8888'

    # environment:
    #   - 'DISPLAY=${hostname}:0'
    #   - 'DISPLAY=localhost:0.0'
    
    working_dir: /work
    command: jupyter lab --ip=0.0.0.0 --allow-root --LabApp.token=''
